### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by chunpu** [chunpu/zhibo#1]
- [x] 域名
  -  准备在 [namecheap](https://www.namecheap.com) 上买, tv 域名 150 左右, 万网 500
  - [x] 先购买 juzhibo.tv, 再选其他的
- [x] 分通栏 (先分为 4 栏), 后续可能添加 `美女`
  - 最热
  - dota2
  - lol
  - 炉石
  - 其他
- [ ] 日志保存(即为重要)
- [ ] 更多的平台选择
  - 17173, 风云直播
  - 选区更好的页面, 比如不用首页用 list 页抓取
- [ ] suggest
  - 人名 suggest, 为什么是人名, 因为 title 都是乱取的, 没啥用
- [ ] 报警
  - 检测页面变化, 如抓取页面元素 class 变化
  - ip 被屏蔽
  - 同时 平台经常维护, 要分清是否是维护还是抓取错误
  - 准备暂时只用 微信 qq 邮箱的方式报警
- [ ] 微博
  - 提供最基本的 timeline 信息, 如
    > 冷女神在斗鱼开始dota2直播啦
- [ ] 微信
  - 提供订阅消息 (好像有条数限制)
  - h5 页面适配
- [ ] 数据库 (上线之后的事)
  - 人物数据库
  - timeline 数据库
  - 数据分析可视化
- [ ] 自己的数据也要防止被抓取
- [ ] 支持过滤，能够快速找到自己想要的网站
- [ ] 增加微博微信分享功能
- [x] 网站访问统计
- [ ] 添加各直播网站导航
- [ ] 智能剔除其实不在直播的节目 
- [x] SEO
- [ ] ICON AND LOGO
- [ ] 更多分类，满足叶少需求（看真球）
- [x] 关键词，热门搜索
- [ ] 个性化订阅
- [x] 美女色情游戏主播list
- [ ] 电视台
- [ ] 体育直播
